// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	admin "yonth_station_backend/api/internal/handler/admin"
	application "yonth_station_backend/api/internal/handler/application"
	auth "yonth_station_backend/api/internal/handler/auth"
	chat "yonth_station_backend/api/internal/handler/chat"
	station "yonth_station_backend/api/internal/handler/station"
	user "yonth_station_backend/api/internal/handler/user"
	"yonth_station_backend/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/admin/application/audit",
				Handler: admin.AuditApplicationHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/admin/application/list",
				Handler: admin.AdminGetApplicationListHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/admin/dashboard",
				Handler: admin.AdminGetDashboardHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/admin/station/:stationId",
				Handler: admin.AdminUpdateStationHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/admin/station/list",
				Handler: admin.AdminGetStationListHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/application/apply",
				Handler: application.ApplyHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/application/cancel/:applicationId",
				Handler: application.CancelApplicationHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/application/checkin",
				Handler: application.CheckinHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/application/checkout",
				Handler: application.CheckoutHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/application/detail/:applicationId",
				Handler: application.GetApplicationDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/application/my-list",
				Handler: application.GetMyApplicationsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/application/payment/notify",
				Handler: application.PaymentNotifyHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/application/refund/:applicationId",
				Handler: application.RefundDepositHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/auth/login",
				Handler: auth.LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/auth/register",
				Handler: auth.RegisterHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/chat/history",
				Handler: chat.GetHistoryHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/chat/users",
				Handler: chat.GetUsersHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/chat/ask",
				Handler: chat.AskHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/chat/knowledge/upload",
				Handler: chat.UploadKnowledgeHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/station/available",
				Handler: station.GetAvailableStationsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/station/comment",
				Handler: station.AddCommentHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/station/comment/list",
				Handler: station.ListCommentsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/station/detail/:stationId",
				Handler: station.GetStationDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/station/like",
				Handler: station.LikeHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/station/like/count/:stationId",
				Handler: station.GetLikeCountHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/station/list",
				Handler: station.GetStationListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/station/unlike",
				Handler: station.UnlikeHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/user/info",
				Handler: user.GetUserInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/user/info",
				Handler: user.UpdateUserInfoHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1"),
	)
}
