// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type AddCommentRequest struct {
	StationId int64  `json:"stationId"`
	Content   string `json:"content"`
	ParentId  int64  `json:"parentId,optional"`
}

type AddCommentResponse struct {
	CommentId int64 `json:"commentId"`
}

type ApplicationDetailResponse struct {
	ApplicationRecord
	UserIdCard string `json:"userIdCard"` // 身份证号（脱敏）
	UserPhone  string `json:"userPhone"`  // 联系电话
	UserSchool string `json:"userSchool"` // 毕业院校
	UserHukou  string `json:"userHukou"`  // 户籍所在地
	AuditBy    string `json:"auditBy"`    // 审核人
	AuditAt    int64  `json:"auditAt"`    // 审核时间戳
}

type ApplicationListRequest struct {
	PageRequest
	Status    *int32 `json:"status,optional"`    // 状态筛选（可选）
	StationId int64  `json:"stationId,optional"` // 驿站筛选（可选）
}

type ApplicationListResponse struct {
	PageResponse
	List []ApplicationRecord `json:"list"`
}

type ApplicationRecord struct {
	ApplicationId int64  `json:"applicationId"` // 申请ID
	UserId        int64  `json:"userId"`        // 申请人ID
	UserName      string `json:"userName"`      // 申请人姓名
	StationId     int64  `json:"stationId"`     // 驿站ID
	StationName   string `json:"stationName"`   // 驿站名称
	CheckinDate   string `json:"checkinDate"`   // 计划入住日期
	CheckoutDate  string `json:"checkoutDate"`  // 计划退房日期
	Status        *int32 `json:"status"`        // 申请状态
	StatusDesc    string `json:"statusDesc"`    // 状态描述
	VisitPurpose  int32  `json:"visitPurpose"`  // 来访目的
	RejectReason  string `json:"rejectReason"`  // 拒绝原因（状态为拒绝时有值）
	DepositAmount int64  `json:"depositAmount"` // 押金金额（分）
	DepositStatus int32  `json:"depositStatus"` // 押金状态：0-未缴纳，1-已缴纳，2-已退还
	CheckinAt     int64  `json:"checkinAt"`     // 实际入住时间戳
	CheckoutAt    int64  `json:"checkoutAt"`    // 实际退房时间戳
	AppliedAt     int64  `json:"appliedAt"`     // 申请时间戳
	UpdatedAt     int64  `json:"updatedAt"`     // 最后更新时间戳
}

type ApplicationRequest struct {
	StationId     int64           `json:"stationId"`              // 申请的驿站ID
	CheckinDate   string          `json:"checkinDate"`            // 计划入住日期（YYYY-MM-DD）
	CheckoutDate  string          `json:"checkoutDate"`           // 计划退房日期（最多7天后）
	VisitPurpose  int32           `json:"visitPurpose"`           // 来访目的：1-求职，2-创业，3-研学
	InterviewInfo *InterviewProof `json:"interviewInfo,optional"` // 面试通知证明（求职时必填）
	BusinessPlan  string          `json:"businessPlan,optional"`  // 创业计划简介（创业时必填）
	Remark        string          `json:"remark,optional"`        // 备注说明
}

type ApplyResponse struct {
	ApplicationId int64  `json:"applicationId"` // 申请ID
	Status        int32  `json:"status"`        // 申请状态：0-待审核
	Message       string `json:"message"`       // 提示信息
}

type AuditRequest struct {
	ApplicationId int64  `json:"applicationId"`         // 申请ID
	Result        int32  `json:"result"`                // 审核结果：1-通过，2-拒绝
	RejectReason  string `json:"rejectReason,optional"` // 拒绝原因（拒绝时必填）
}

type BaseResponse struct {
	Code    int32       `json:"code"`    // 业务状态码：0-成功，其他-失败
	Message string      `json:"message"` // 状态描述信息
	Data    interface{} `json:"data"`    // 响应数据
}

type CancelApplicationRequest struct {
	ApplicationId int64 `path:"applicationId"` // 申请ID，从路径参数获取
}

type CheckinRequest struct {
	ApplicationId int64 `json:"applicationId"` // 申请ID
}

type CheckoutRequest struct {
	ApplicationId int64 `json:"applicationId"` // 申请ID
}

type CommentItem struct {
	Id        int64  `json:"id"`
	UserId    int64  `json:"userId"`
	UserName  string `json:"userName"`
	Content   string `json:"content"`
	ParentId  int64  `json:"parentId"`
	CreatedAt int64  `json:"createdAt"`
}

type CommentListRequest struct {
	StationId int64 `form:"stationId"`
	Page      int32 `form:"page,default=1"`
	PageSize  int32 `form:"pageSize,default=20"`
}

type CommentListResponse struct {
	Total int64         `json:"total"`
	List  []CommentItem `json:"list"`
}

type GetApplicationDetailRequest struct {
	ApplicationId int64 `path:"applicationId"` // 申请ID，从路径参数获取
}

type GetLikeCountRequest struct {
	StationId int64 `path:"stationId"`
}

type GetStationDetailRequest struct {
	StationId int64 `path:"stationId"` // 驿站ID，从路径参数获取
}

type InterviewProof struct {
	Type    int32  `json:"type"`    // 证明类型：1-面试邮件，2-截图，3-公告，4-函件
	Content string `json:"content"` // 证明内容（URL或文字）
	FileUrl string `json:"fileUrl"` // 证明文件URL
}

type LikeRequest struct {
	StationId int64 `json:"stationId"`
}

type LikeResponse struct {
	Count int64 `json:"count"`
}

type LoginRequest struct {
	Account  string `json:"account"`
	Password string `json:"password"`
}

type LoginResponse struct {
	Token     string `json:"token"`
	ExpiresAt int64  `json:"expiresAt"`
	UserId    int64  `json:"userId"`
	UserName  string `json:"userName"`
	IsAdmin   bool   `json:"isAdmin"`
}

type PageRequest struct {
	Page     int32 `json:"page,default=1"`      // 当前页码，默认第1页
	PageSize int32 `json:"pageSize,default=20"` // 每页条数，默认20条
}

type PageResponse struct {
	Total    int64         `json:"total"`    // 总记录数
	Page     int32         `json:"page"`     // 当前页码
	PageSize int32         `json:"pageSize"` // 每页条数
	List     []interface{} `json:"list"`     // 数据列表
}

type PaymentNotifyRequest struct {
	ApplicationId int64  `json:"applicationId"` // 申请ID
	TradeNo       string `json:"tradeNo"`       // 支付流水号
	Amount        int64  `json:"amount"`        // 支付金额（分）
	PayTime       int64  `json:"payTime"`       // 支付时间戳
}

type RefundDepositRequest struct {
	ApplicationId int64 `path:"applicationId"` // 申请ID，从路径参数获取
}

type RegisterRequest struct {
	UserName string `json:"userName"`
	Password string `json:"password"`
	Phone    string `json:"phone,optional"`
	IsAdmin  bool   `json:"isAdmin,optional"`
}

type RegisterResponse struct {
	Token     string `json:"token"`
	ExpiresAt int64  `json:"expiresAt"`
	UserId    int64  `json:"userId"`
	UserName  string `json:"userName"`
	IsAdmin   bool   `json:"isAdmin"`
}

type StationDetailResponse struct {
	StationInfo
	AverageRating  float32 `json:"averageRating"`  // 平均评分
	TotalReviews   int32   `json:"totalReviews"`   // 评价总数
	WeeklyQuota    int32   `json:"weeklyQuota"`    // 每周配额
	RemainingQuota int32   `json:"remainingQuota"` // 本周剩余名额
}

type StationInfo struct {
	StationId      int64   `json:"stationId"`      // 驿站ID
	StationName    string  `json:"stationName"`    // 驿站名称
	District       string  `json:"district"`       // 所属区域（东湖区/西湖区等）
	Address        string  `json:"address"`        // 详细地址
	Latitude       float64 `json:"latitude"`       // 纬度坐标
	Longitude      float64 `json:"longitude"`      // 经度坐标
	ContactPhone   string  `json:"contactPhone"`   // 联系电话
	BusinessHours  string  `json:"businessHours"`  // 服务时间（如：8:30-18:00）
	TotalRooms     int32   `json:"totalRooms"`     // 总房间数
	AvailableRooms int32   `json:"availableRooms"` // 可预约房间数
	Status         *int32  `json:"status"`         // 状态：0-关闭，1-运营中
	Description    string  `json:"description"`    // 驿站介绍
	Amenities      string  `json:"amenities"`      // 配套设施（JSON字符串）
	NearbyMetro    string  `json:"nearbyMetro"`    // 附近地铁站
	ImageUrl       string  `json:"imageUrl"`       // 驿站图片URL
}

type StationListRequest struct {
	PageRequest
	District string `json:"district,optional"` // 区域筛选（可选）
	Status   int32  `json:"status,optional"`   // 状态筛选（可选）
}

type StationListResponse struct {
	PageResponse
	List []StationInfo `json:"list"`
}

type UpdateUserInfoRequest struct {
	UserName     string `json:"userName,optional"`     // 用户姓名（可选）
	BirthDate    string `json:"birthDate,optional"`    // 出生日期（可选）
	Gender       int32  `json:"gender,optional"`       // 性别（可选）
	Education    int32  `json:"education,optional"`    // 学历（可选）
	School       string `json:"school,optional"`       // 毕业院校（可选）
	GraduateYear int32  `json:"graduateYear,optional"` // 毕业年份（可选）
	HukouCity    string `json:"hukouCity,optional"`    // 户籍所在地（可选）
}

type UserInfoResponse struct {
	UserId       int64  `json:"userId"`       // 用户ID
	UserName     string `json:"userName"`     // 用户姓名
	Phone        string `json:"phone"`        // 手机号码（脱敏）
	IdCard       string `json:"idCard"`       // 身份证号（脱敏）
	BirthDate    string `json:"birthDate"`    // 出生日期（YYYY-MM-DD）
	Gender       int32  `json:"gender"`       // 性别：0-未知，1-男，2-女
	Education    int32  `json:"education"`    // 学历：1-大专，2-本科，3-硕士，4-博士
	School       string `json:"school"`       // 毕业院校
	GraduateYear int32  `json:"graduateYear"` // 毕业年份
	HukouCity    string `json:"hukouCity"`    // 户籍所在地城市
	Status       int32  `json:"status"`       // 账号状态：0-正常，1-冻结
	IsAdmin      bool   `json:"isAdmin"`      // 是否管理员
	CreatedAt    int64  `json:"createdAt"`    // 注册时间戳
}

// ---------- 智能客服 ----------
type ChatRequest struct {
	Question  string `json:"question"`
	SessionId string `json:"sessionId,optional"`
}

type ChatResponse struct {
	Answer    string `json:"answer"`
	SessionId string `json:"sessionId"`
}

type KnowledgeUploadRequest struct {
	Title    string `json:"title"`
	Content  string `json:"content"`
	Category string `json:"category,optional"`
}

type KnowledgeUploadResponse struct {
	DocId   string `json:"docId"`
	Message string `json:"message"`
}
